FAST-gamsungcoding/FE_MiniProject

src/app/cart/cart.module.scss, src/app/cart/layout.tsx, src/app/cart/page.tsx, src/components/button/button.scss, src/components/button/buttonType.ts, src/components/button/index.tsx
Cart의 전체적인 레이아웃을 구현하고 Button 컴포넌트 문제들을 수정했습니다
체크박스 컴포넌트를 먼저 구현할 예정입니다!
=> [Style] Cart 전체 레이아웃 구현

src/components/atoms/button/button.stories.tsx, src/components/atoms/button/buttonType.ts, src/components/atoms/button/index.tsx
Link Button을 추가적으로 구현하였습니다 만약 클릭했을 때 단순히 페이지 이동이라면 type과 href 설정을 통해 Link Button 사용하시면 됩니다
제가 일단 스토리북으로만 확인했는데 안되는 거 있으시면 말씀해주세요
=> [Feat] Link Button 구현

src/app/(header)/(narrow-view)/cart/_components/cart-footer/cartFooter.stories.tsx, src/app/(header)/(narrow-view)/cart/_components/cart-footer/cartFooterType.ts, src/app/(header)/(narrow-view)/cart/_components/cart-footer/index.tsx, src/app/(header)/(narrow-view)/cart/_components/cart-group/cartGroup.stories.tsx, src/app/(header)/(narrow-view)/cart/_components/cart-group/cartGroupType.ts, src/app/(header)/(narrow-view)/cart/_components/cart-group/index.tsx, src/app/(header)/(narrow-view)/cart/_components/cart-item/cartItem.stories.tsx, src/app/(header)/(narrow-view)/cart/_components/cart-item/cartItemType.ts, src/app/(header)/(narrow-view)/cart/_components/cart-item/index.tsx, src/app/(header)/(narrow-view)/cart/cart.stories.tsx, src/app/(header)/(narrow-view)/cart/cartType.ts, src/app/(header)/(narrow-view)/cart/page.tsx, src/components/atoms/button/buttonType.ts, src/components/atoms/button/index.tsx
type="Link"로 지정해야지 Link Button이 아닌, href만 넘겨줘도 Link Button을 return하도록 변경했습니다
type에는 "button" | "submit"|"reset" 이 할당될 수 있고 기본값은 button입니다
=> [Chore] Button type 속성 추가

src/api/index.ts, src/api/signUp/index.ts, src/app/(non-header)/sign-up/_components/signUpForm/index.tsx, src/app/(non-header)/sign-up/_components/signUpForm/signUpForm.module.scss, src/app/(non-header)/sign-up/_components/signUpForm/signUpType.ts, src/components/atoms/input/index.tsx, src/components/atoms/input/input.scss, src/components/atoms/input/inputType.ts
현재 로직 날것 그대로의 상황입니다.
~~아직 서버 연결이 500 에러인 상황이라 테스트를 진행해보진 못했지만,
성공 상황과 에러 상황에 맞도록 메세지가 나타날 수 있게 했습니다.~~
=> [Feat] 회원가입 페이지 유효성 검사기능 추가

next.config.js, package-lock.json, package.json, src/api/cart/cartApiType.ts, src/app/(header)/(narrow-view)/cart/_components/cart-footer/cartFooter.stories.tsx, src/app/(header)/(narrow-view)/cart/_components/cart-footer/cartFooterType.ts, src/app/(header)/(narrow-view)/cart/_components/cart-footer/index.tsx, src/app/(header)/(narrow-view)/cart/_components/cart-group/cartGroup.module.scss, src/app/(header)/(narrow-view)/cart/_components/cart-group/index.tsx, src/app/(header)/(narrow-view)/cart/_components/cart-item/cartItem.stories.tsx, src/app/(header)/(narrow-view)/cart/_components/cart-item/index.tsx, src/app/(header)/(narrow-view)/cart/cart.tsx, src/hooks/cart/useCart.ts, src/recoil/order.ts, src/recoil/productType.ts
예약하기 버튼 클릭하면 recoil 상태에 item 정보를 담습니다
=> [Feat] 예약하기 구현

src/app/(header)/(wide-view)/rooms/[id]/_component/cart-modal/cartModal.module.scss, src/app/(header)/(wide-view)/rooms/[id]/_component/cart-modal/cartModal.tsx, src/app/(header)/(wide-view)/rooms/[id]/_component/reservation/index.tsx, src/app/(header)/(wide-view)/rooms/[id]/_component/reservation/reservationType.ts, src/app/layout.tsx
=> [Fix] 상세페이지 Reservation 렌더링 오류 Fix

src/api/main/index.ts, src/api/main/mainApiType.ts, src/app/(header)/(wide-view)/main/_components/item-list/index.tsx, src/app/(header)/(wide-view)/main/_components/item-list/itemListType.ts, src/app/(header)/(wide-view)/main/_components/item/index.tsx, src/app/(header)/(wide-view)/main/_components/item/itemType.ts, src/app/(header)/(wide-view)/main/page.tsx, src/hooks/main/useMain.ts, src/queries/main/index.ts
가현님께 무한감사,, 체고가현,,짱가현,,천재가현,,🥹💦
=> [Feat] 메인 무한스크롤 추가

src/Provider.tsx, src/styles/mobile.module.scss
=> [Style] 모바일 반응형 

src/api/index.ts, src/app/(header)/(wide-view)/rooms/[id]/_component/reservation/index.tsx
=> [Fix]상세페이지 예약하기 체크인체크아웃날짜 동일하게 예약되는부분  해결

src/api/index.ts, src/api/reservation/index.ts, src/api/reservation/reservationApiType.ts, src/app/(header)/(narrow-view)/reservation-check/page.tsx, src/app/(header)/(narrow-view)/reservation/page.tsx, src/components/atoms/checkbox/checkboxType.ts, src/components/atoms/checkbox/index.tsx, src/components/atoms/input/index.tsx, src/components/atoms/input/inputType.ts, src/queries/cart/index.ts, src/queries/reservation/useReservation.ts, src/recoil/productType.ts, src/recoil/successProducts.ts
=> [Fix] 예약하기 오류 수정

src/app/(header)/(narrow-view)/cart/cart.tsx, src/app/(header)/(narrow-view)/reservation-list/reservationList.tsx, src/app/(header)/(wide-view)/main/_components/item-list/index.tsx, src/components/layouts/loader/index.tsx, src/components/layouts/loader/loader.module.scss
=> [Style] loader 추가

src/app/(header)/(narrow-view)/reservation-check/page.tsx
=> Chore: 주석처리 제거

src/app/(header)/(narrow-view)/cart/_components/cart-footer/index.tsx, src/app/(header)/(narrow-view)/cart/_components/cart-item/index.tsx, src/hooks/cart/useCart.ts
cartData를 서버로부터 받아온 후 setSelectedItems를 실행해서 처음 렌더링 화면에서 모든 상품이 전체 선택되게 구현했습니다
상품을 선택하지 않을 시 예약하기 버튼을 disabled 처리했습니다
가격 콤마 처리해줬습니다
=> [Refactor] 장바구니 페이지 예약하기 버튼 및 전체 선택 리팩토링

src/app/(header)/(narrow-view)/cart/_components/cart-skeleton/index.tsx, src/app/(header)/(narrow-view)/cart/cart.module.scss, src/app/(header)/(narrow-view)/cart/cart.tsx, src/hooks/cart/useCart.ts
장바구니 페이지에 스켈레톤을 구현했는데,, 장바구니에 상품이 아예 없을 경우가 있으니까 loader가 더 적합할 지 고민입니다
=> [Feat] 장바구니 페이지 스켈레톤 구현

src/api/rooms/index.ts, src/api/rooms/roomsApiType.ts, src/app/(header)/(wide-view)/rooms/[id]/_component/carousel/carousel.module.scss, src/app/(header)/(wide-view)/rooms/[id]/_component/carousel/carouselType.ts, src/app/(header)/(wide-view)/rooms/[id]/_component/carousel/index.tsx, src/app/(header)/(wide-view)/rooms/[id]/_component/cart-modal/cartModal.tsx, src/app/(header)/(wide-view)/rooms/[id]/_component/cart-modal/cartModalType.ts, src/app/(header)/(wide-view)/rooms/[id]/_component/custom-calendar/index.tsx, src/app/(header)/(wide-view)/rooms/[id]/_component/detail-page/detailPage.tsx, src/app/(header)/(wide-view)/rooms/[id]/_component/reservation/index.tsx
1주차 스프린트 목표었던 오류들과 추가로 멘토님의 코드리뷰 기반으로 리팩토링을 진행하였습니다.
=> [Refactor] 상세페이지 리팩토링

src/app/(header)/(narrow-view)/cart/_components/cart-footer/cartFooter.module.scss, src/app/(header)/(narrow-view)/cart/_components/cart-group/cartGroup.module.scss, src/app/(header)/(narrow-view)/cart/_components/cart-item/cartItem.module.scss, src/app/(header)/(narrow-view)/cart/_components/cart-item/index.tsx, src/app/(header)/(narrow-view)/cart/_components/cart-item/soldOutCartItem.tsx, src/components/atoms/button/button.scss, src/components/atoms/button/buttonType.ts, src/components/atoms/button/index.tsx, src/components/atoms/text/index.tsx, src/components/atoms/text/text.scss
장바구니 페이지 반응형 구현했습니다
버튼은 size가 lg일때만 반응형 속성을 줘서 나머지는 각자 하시면 될 것 같아요
텍스트의 모든 rem을 em으로 바꾸고 wrapper도 추가했습니다!
=> [Style] 장바구니 페이지 반응형 구현

src/app/(header)/(narrow-view)/cart/_components/cart-group/cartGroup.module.scss, src/app/(header)/(narrow-view)/cart/_components/cart-group/index.tsx, src/app/(header)/(narrow-view)/cart/cart.module.scss, src/app/(header)/(narrow-view)/cart/cart.tsx, src/app/(header)/(narrow-view)/reservation-list/_components/reservation-item/page.tsx, src/app/(header)/(narrow-view)/reservation-list/_components/reservation-item/reservationItem.module.scss, src/app/(header)/(narrow-view)/reservation-list/_components/reservation-list-title/reservationListTitle.module.scss, src/hooks/cart/useCart.ts, src/hooks/cart/useSelect.ts, src/recoil/selectedItem.ts
=> [Style] 주문 내역 확인하기 페이지 반응형 구현

src/app/(header)/(wide-view)/rooms/[id]/_component/carousel/carousel.module.scss, src/app/(header)/(wide-view)/rooms/[id]/_component/carousel/index.tsx, src/app/(header)/(wide-view)/rooms/[id]/_component/custom-calendar/customCalendar.module.scss, src/app/(header)/(wide-view)/rooms/[id]/_component/custom-calendar/index.tsx, src/app/(header)/(wide-view)/rooms/[id]/_component/detail-description/detailDescription.module.scss, src/app/(header)/(wide-view)/rooms/[id]/_component/detail-description/detailDescription.tsx, src/app/(header)/(wide-view)/rooms/[id]/_component/detail-page/detailPage.module.scss, src/app/(header)/(wide-view)/rooms/[id]/_component/detail-page/detailPage.tsx, src/app/(header)/(wide-view)/rooms/[id]/_component/reservation/index.tsx, src/app/(header)/(wide-view)/rooms/[id]/_component/reservation/reservation.module.scss
=> [Refactor] : 상세페이지 리팩토링

src/app/(header)/(narrow-view)/reservation-check/_components/detail-titles/detailTitles.module.scss, src/app/(header)/(narrow-view)/reservation/page.tsx
- 코드 리뷰 남겨주신거 반영해서 네이밍 새로 하고, 필요 없는 파일 및 폴더 삭제하고, 예약하기 페이지에 있는 버그 수정하였습니다.
=> [Refactor] 코드 리뷰 반영

src/app/(header)/(narrow-view)/reservation-check/page.tsx, src/app/(header)/(narrow-view)/reservation-check/reservationCheck.module.scss, src/app/(header)/(narrow-view)/reservation/page.tsx, src/app/(header)/(narrow-view)/reservation/reservation.module.scss, src/components/atoms/button/button.scss, src/components/atoms/input/input.scss
=> [Refactor] 예약하기, 예약확인하기 반응형 수정
